### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Nugine** [Nugine/zuc#1]
## Milestone 1: Correctness

+ [x] ZUC128 keystream generator
  + [GB/T 33133.1-2016](https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=8C41A3AEECCA52B5C0011C8010CF0715)
+ [x] 128-EEA3 confidentiality algorithm
  + [GB/T 33133.2-2021](https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=5D3CBA3ADEC7989344BD1E63006EF2B3)
  + https://www.gsma.com/solutions-and-impact/technologies/security/wp-content/uploads/2019/05/EEA3_EIA3_specification_v1_8.pdf
+ [x] 128-EIA3 integrity algorithm 
  + [GB/T 33133.3-2021](https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=C6D60AE0A7578E970EF2280ABD49F4F0)
  + https://www.gsma.com/solutions-and-impact/technologies/security/wp-content/uploads/2019/05/EEA3_EIA3_specification_v1_8.pdf
+ [x] ZUC256 keystream generator
  + http://www.is.cas.cn/ztzl2016/zouchongzhi/201801/W020180416526664982687.pdf
+ [x] ZUC256 MAC generation
  + http://www.is.cas.cn/ztzl2016/zouchongzhi/201801/W020180416526664982687.pdf

## Milestone 2: RustCrypto

+ [x] ZUC128/256 stream cipher ([cipher::StreamCipherCore])
+ [x] ZUC128/256 MAC ([digest::MAC])
+ [x] 128-EEA3 ([cipher::StreamCipherCore])
+ [x] 128-EIA3 ([digest::MAC])

[cipher::StreamCipherCore]: https://docs.rs/cipher/latest/cipher/trait.StreamCipherCore.html
[digest::MAC]: https://docs.rs/digest/latest/digest/trait.Mac.html

## Milestone 3: SIMD

+ [x] benchmark: ZUC128 keystream generation
  + measure the performance (bytes per second) of ZUC128 keystream generator
  + https://bheisler.github.io/criterion.rs/book/criterion_rs.html
+ [x] benchmark: 128-EIA3
+ [ ] #14
+ [ ] #15
+ [ ] #38

## Milestone 4: Quality

+ [x] basic docs
+ [ ] #32
+ [x] #26 
+ [ ] #28 
+ [x] #30 
+ [ ] #37

## References

+ https://github.com/CrayfishGo/gm-rs
  + https://github.com/CrayfishGo/gm-rs/tree/main/gm-zuc
+ https://github.com/guanzhi/GmSSL
  + https://github.com/guanzhi/GmSSL/blob/master/src/zuc.c
  + https://github.com/guanzhi/GmSSL/blob/master/src/zuc_modes.c
  + https://github.com/guanzhi/GmSSL/blob/master/tests/zuctest.c
+ https://github.com/emmansun/gmsm
  + https://github.com/emmansun/gmsm/wiki/Efficient-Software-Implementations-of-ZUC
+ https://github.com/intel/intel-ipsec-mb
+ https://github.com/Tongsuo-Project/Tongsuo
  + https://www.yuque.com/tsdoc/ts/copzp3#
  + https://github.com/Tongsuo-Project/rust-tongsuo/issues/2

**Comment by Nugine** [comment]
## Rewards for solving todo items

|Reward (CNY)|impl|tests|docs|
|:-:|-:|-:|-:|
|128-EEA3|100|30|20|
|128-EIA3|100|30|20|
|ZUC256|100|30|20
|ZUC256 SIMD|300|30|20|

**Comment by jackyliu16** [comment]
我写 eea3-128, 吃完饭开始农

**Comment by Xerxes-zhz** [comment]
eia 3

**Comment by pai2shub** [comment]
benchmark: ZUC128 keystream generation https://github.com/Nugine/zuc/pull/7
